exec-once = systemctl --user start hyprpolkitagent
exec-once = waybar & swaync & hypridle & hyprpaper
exec-once = wlsunset -l 39.6 -L -79.9 -t 3200 -T 6500
exec-once = [workspace 1 silent] zen-browser
exec-once = [workspace 2 silent] kitty -e --hold fastfetch
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = HYPRSHOT_DIR,/home/cwilliams0926/Pictures/Screenshots/
