-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("HYPRSHOT_DIR", "/home/cwilliams0926/Pictures/Screenshots/")

-- Autostart
hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("waybar & swaync & hypridle & hyprpaper")
  hl.exec_cmd("wlsunset -l 39.6 -L -79.9 -t 3200 -T 6500")
  hl.exec_cmd("zen-browser")
  hl.exec_cmd("kitty -e --hold fastfetch")
end)
