-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- https://wiki.hypr.land/Configuring/Variables/#general

hl.config({
  general = {
    gaps_in = 4,
    gaps_out = 6,
    border_size = 1,
    -- https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    ["col.active_border"] = "rgb(7daea3)",
    ["col.inactive_border"] = "rgb(a89984)",
    -- Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false,
    -- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = false,
    layout = "dwindle",
  },
})

-- https://wiki.hypr.land/Configuring/Variables/#decoration

hl.config({
  decoration = {
    rounding = 6,
    rounding_power = 2,
    -- Change transparency of focused and unfocused windows
    active_opacity = 1.0,
    inactive_opacity = 1.0,
    shadow = {
      enabled = false,
    },
    -- https://wiki.hypr.land/Configuring/Variables/#blur
    blur = {
      enabled = true,
      size = 10,
      passes = 2,
      new_optimizations = true,
      noise = 0.01,
      contrast = 0.8,
      vibrancy = 0.2,
    },
  },
})

-- https://wiki.hypr.land/Configuring/Variables/#animations

hl.config({
  animations = {
    enabled = true,
    -- Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
    --        NAME,           X0,   Y0,   X1,   Y1
    -- Default animations, see https://wiki.hypr.land/Configuring/Animations/
    --           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
  },
})

-- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more

hl.config({
  dwindle = {
    preserve_split = true,
    -- You probably want this
  },
})

-- See https://wiki.hypr.land/Configuring/Master-Layout/ for more

hl.config({
  master = {
    new_status = "master",
  },
})

-- https://wiki.hypr.land/Configuring/Variables/#misc

hl.config({
  misc = {
    force_default_wallpaper = 0,
    -- Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true,
    -- If true disables the random hyprland logo / anime girl background. :(
  },
})
