-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- https://wiki.hypr.land/Configuring/Variables/#general

hl.config({
  general = {
    gaps_in = 4,
    gaps_out = 6,
    border_size = 1,
    -- https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    ["col.active_border"] = "rgb(1d2021)",
    ["col.inactive_border"] = "rgb(1d2021)",
    -- Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false,
    -- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = false,
    layout = "dwindle",
  },
})

-- https://wiki.hypr.land/Configuring/Variables/#decoration

hl.config({
  decoration = {
    rounding = 24,
    rounding_power = 8,
    -- Change transparency of focused and unfocused windows
    active_opacity = 1.0,
    inactive_opacity = 1.0,
    shadow = {
      enabled = true,
      range = 28,
      render_power = 3,
      color = "rgba(0a0a0a89)",
    },
    -- https://wiki.hypr.land/Configuring/Variables/#blur
    blur = {
      enabled = true,
      size = 10,
      passes = 3,
      new_optimizations = true,
      noise = 0.01,
      contrast = 0.8,
      vibrancy = 0.2,
    },
  },
})

-- https://wiki.hypr.land/Configuring/Variables/#animations

hl.config({
  animations = {
    enabled = true,

    -- Default curves
    hl.curve("easeOutQuint", {
      type = "bezier",
      points = {
        { 0.23, 1 },
        { 0.32, 1 },
      },
    }),
    hl.curve("easeInOutCubic", {
      type = "bezier",
      points = {
        { 0.65, 0.05 },
        { 0.36, 1 },
      },
    }),
    hl.curve("linear", {
      type = "bezier",
      points = {
        { 0, 0 },
        { 1, 1 },
      },
    }),
    hl.curve("almostLinear", {
      type = "bezier",
      points = {
        { 0.5,  0.5 },
        { 0.75, 1 },
      },
    }),
    hl.curve("quick", {
      type = "bezier",
      points = {
        { 0.15, 0 },
        { 0.1,  1 },
      },
    }),
    hl.curve("overshot", {
      type = "bezier",
      points = {
        { 0.05, 0.9 },
        { 0.1,  1.05 },
      },
    }),

    -- Default animations
    hl.animation({
      leaf = "global",
      enabled = true,
      speed = 10,
      bezier = "default",
    }),
    hl.animation({
      leaf = "border",
      enabled = true,
      speed = 5.39,
      bezier = "easeOutQuint",
    }),
    hl.animation({
      leaf = "windows",
      enabled = true,
      speed = 4.79,
      bezier = "easeOutQuint",
    }),
    hl.animation({
      leaf = "windowsIn",
      enabled = true,
      speed = 4.1,
      bezier = "easeOutQuint",
      style = "popin 87%",
    }),
    hl.animation({
      leaf = "windowsOut",
      enabled = true,
      speed = 1.49,
      bezier = "linear",
      style = "popin 87%",
    }),
    hl.animation({
      leaf = "fadeIn",
      enabled = true,
      speed = 1.73,
      bezier = "almostLinear",
    }),
    hl.animation({
      leaf = "fadeOut",
      enabled = true,
      speed = 1.46,
      bezier = "almostLinear",
    }),
    hl.animation({
      leaf = "fade",
      enabled = true,
      speed = 3.03,
      bezier = "quick",
    }),
    hl.animation({
      leaf = "layers",
      enabled = true,
      speed = 3.81,
      bezier = "easeOutQuint",
    }),
    hl.animation({
      leaf = "layersIn",
      enabled = true,
      speed = 4,
      bezier = "easeOutQuint",
      style = "fade",
    }),
    hl.animation({
      leaf = "layersOut",
      enabled = true,
      speed = 1.5,
      bezier = "linear",
      style = "fade",
    }),
    hl.animation({
      leaf = "fadeLayersIn",
      enabled = true,
      speed = 1.79,
      bezier = "almostLinear",
    }),
    hl.animation({
      leaf = "fadeLayersOut",
      enabled = true,
      speed = 1.39,
      bezier = "almostLinear",
    }),
    hl.animation({
      leaf = "workspaces",
      enabled = true,
      speed = 3,
      bezier = "overshot",
      style = "slidefade 30%",
    }),
    hl.animation({
      leaf = "zoomFactor",
      enabled = true,
      speed = 7,
      bezier = "quick",
    }),
  },
})

-- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more

hl.config({
  dwindle = {
    preserve_split = true,
    -- You probably want this
  },
})

-- See https://wiki.hypr.land/Configuring/Master-Layout/ for more

hl.config({
  master = {
    new_status = "master",
  },
})

-- https://wiki.hypr.land/Configuring/Variables/#misc

hl.config({
  misc = {
    force_default_wallpaper = 0,
    -- Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true,
    -- If true disables the random hyprland logo / anime girl background. :(
  },
})
