-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local terminal = "kitty"

local fileManager = "pcmanfm"

local menu = "rofi -show drun -display-drun  -show-icons"
