-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.window_rule({
  name = "suppress-maximize-events",
  match = {
    class = ".*",
  },
  suppress_event = "maximize",
})

hl.window_rule({
  name = "fix-xwayland-drags",
  match = {
    class = "^$",
    title = "^$",
    xwayland = true,
    float = true,
    fullscreen = false,
    pin = false,
  },
  no_focus = true,
})

-- Hyprland-run windowrule

hl.window_rule({
  name = "move-hyprland-run",
  match = {
    class = "hyprland-run",
  },
  move = { 20, "monitor_h-120" },
  float = true,
})

hl.workspace_rule({
  workspace = 1,
  monitor = "eDP-1",
})

hl.workspace_rule({
  workspace = 2,
  monitor = "eDP-1",
})

hl.workspace_rule({
  workspace = 3,
  monitor = "eDP-1",
})

hl.workspace_rule({
  workspace = 4,
  monitor = "eDP-1",
})

hl.layer_rule({
  match = {
    namespace = "waybar",
  },
  blur = true,
})

hl.layer_rule({
  match = {
    namespace = "waybar",
  },
  ignore_alpha = 0,
})

hl.layer_rule({
  match = {
    namespace = "^rofi$",
  },
  blur = true,
})

hl.layer_rule({
  match = {
    namespace = "^rofi$",
  },
  ignore_alpha = 0,
})

hl.window_rule({
  name = "workspace_1",
  match = {
    class = "^(?i).*zen-browser.*",
  },
  workspace = 1,
})

hl.window_rule({
  name = "workspace_2",
  match = {
    class = "^(?i).*kitty.*",
  },
  workspace = 2,
})

hl.window_rule({
  name = "workspace_3",
  match = {
    class = "^(?i).*discord.*",
  },
  workspace = 3,
})

hl.window_rule({
  name = "workspace_4",
  match = {
    class = "^(?i).*nautilus.*",
  },
  workspace = 4,
})
