windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

workspace = 1, monitor:eDP-1
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1

layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0, match:namespace waybar
layerrule = blur on, match:namespace ^rofi$
layerrule = ignore_alpha 0, match:namespace ^rofi$

windowrule = workspace 1, match:class ^(?i).*zen-browser.*

windowrule = workspace 2, match:class ^(?i).*kitty.*

windowrule = workspace 3, match:class ^(?i).*discord.*

windowrule = workspace 4, match:class ^(?i).*pcmanfm.*

