#!/usr/bin/env bash

DECOR_DIR="$HOME/.config/hypr/modules/decorations"
CURRENT_LINK="$DECOR_DIR/current.lua"

choice=$(printf "Rounded\nBoxed\nRounded-Borders" | rofi -dmenu \
  -p "Change Decoration" \
  -theme-str 'listview { columns: 1; lines: 6; orientation: horizontal; }' \
  -theme-str 'element-text { vertical-align: 0.5; horizontal-align: 0.0; }' \
  -theme-str 'element-icon { size: 0px; }' 
)

[ -z "$choice" ] && exit 0

ln -sf "$DECOR_DIR/$choice.lua" "$CURRENT_LINK"
hyprctl reload
notify-send "Hyprland" "Decorations switched to: $choice"
