#!/usr/bin/env bash
DECOR_DIR="$HOME/.config/hypr/modules/decorations"
CURRENT_LINK="$DECOR_DIR/current.lua"

GLASS_DIR="$HOME/.config/hypr/modules/decorations/"
GLASS_LINK="$GLASS_DIR/glass-current.lua"

choice=$(printf "Rounded\nBoxed\nRounded-Borders\nGlass On\nGlass Off" | rofi -dmenu \
  -p "Change Decoration" \
  -theme-str 'listview { columns: 1; lines: 6; orientation: horizontal; }' \
  -theme-str 'element-text { vertical-align: 0.5; horizontal-align: 0.0; }' \
  -theme-str 'element-icon { size: 0px; }' 
)
[ -z "$choice" ] && exit 0

case "$choice" in
  "Glass On")
    ln -sf "$GLASS_DIR/glass-on.lua" "$GLASS_LINK"
    ;;
  "Glass Off")
    ln -sf "$GLASS_DIR/glass-off.lua" "$GLASS_LINK"
    ;;
  *)
    ln -sf "$DECOR_DIR/$choice.lua" "$CURRENT_LINK"
    ;;
esac

hyprctl reload
notify-send "Hyprland" "Decorations switched to: $choice"
