#!/usr/bin/bash

if pidof wlsunset; then
  notify-send -i "/home/cwilliams0926/.config/swaync/icons/dark_mode.svg" "Night Light Off" "Night light turned off" &&
  killall wlsunset
else
  notify-send -i "/home/cwilliams0926/.config/swaync/icons/dark_mode.svg" "Night Light On" "Night light turned on" &&
  wlsunset -T 4001
fi

