$bg = rgb(222222)
$bgalt = rgb(333333)
$bgtray = rgb(383838)

$fg = rgb(ebdbb2)
$fgsoft = rgb(fff4d2)
$fgsoftAlpha = fff4d2

$border = rgb(585858)
$gray = rgb(555555)

$black = rgb(000000)

$blue = rgb(83a598)
$bluedark = rgb(458588)

$pink = rgb(d3869b)
$pinkdark = rgb(b26286)

$green = rgb(8ec07c)
$greenAlpha = 8ec07c
$greendark = rgb(689d68)

$red = rgb(ea6962)
$reddark = rgb(cc241d)
$redcritical = rgb(b22222)

$orange = rgb(e78a4e)
$accent = rgb(e78a4e)
$accentAlpha = e78a4e
$font = JetBrainsMono Nerd Font

# GENERAL
general {
    disable_loading_bar = true
    hide_cursor = true
}

# BACKGROUND
background {
    monitor =
    path = ~/.config/backgrounds/bachlanschaft_hormann_1840.jpg
    blur_passes = 2
    color = $base
}

# TIME
label {
    monitor =
    text = cmd[update:30000] echo "$(date +"%R")"
    color = $fgsoft
    font_size = 90
    font_family = $font
    position = -30, 0
    halign = right
    valign = top
}

# DATE 
label {
    monitor = 
    text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
    color = $fgsoft
    font_size = 25
    font_family = $font
    position = -30, -150
    halign = right
    valign = top
}

# USER AVATAR

image {
    monitor = 
    path = ~/.face
    size = 100
    border_color = $accent

    position = 0, 75
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $green
    inner_color = $bgalt
    font_color = $fgsoft
    fade_on_empty = false
    placeholder_text = <span foreground="##$fgsoftAlpha"><i>󰌾 Logged in as </i><span foreground="##$greenAlpha">$USER</span></span>
    hide_input = false
    check_color = $accent
    fail_color = $red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = $accent
    position = 0, -35
    halign = center
    valign = center
}
