-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local monitors = require("modules.monitors")

local input = require("modules.input")

local programs = require("modules.programs")

local lookAndFeel = require("modules.lookAndFeel")

local binds = require("modules.binds")

local windows = require("modules.windows")

local autostart = require("modules.autostart")
