set -g @thm_bg "#cccccc"
set -g @thm_fg "#333333"
set -g @thm_mantle "#c2c2c2"
set -g @thm_crust "#cccccc"
set -g @thm_surface_0 "#b8b8b8"
set -g @thm_surface_1 "#aeaeae"
set -g @thm_surface_2 "#a4a4a4"
set -g @thm_overlay_0 "#a4a4a4"
set -g @thm_overlay_1 "#474747"
set -g @thm_overlay_2 "#4a4a4a"
set -g @thm_subtext_0 "#545454"
set -g @thm_subtext_1 "#333333"
set -g @thm_red "#9a9a9a"
set -g @thm_maroon "#9a9a9a"
set -g @thm_peach "#909090"
set -g @thm_yellow "#868686"
set -g @thm_green "#7c7c7c"
set -g @thm_teal "#727272"
set -g @thm_sky "#727272"
set -g @thm_sapphire "#686868"
set -g @thm_blue "#686868"
set -g @thm_lavender "#686868"
set -g @thm_mauve "#5e5e5e"
set -g @thm_pink "#5e5e5e"
set -g @thm_flamingo "#9a9a9a"
set -g @thm_rosewater "#333333"

