set -g @thm_bg "#16161d"
set -g @thm_fg "#dcd7ba"
set -g @thm_mantle "#1f1f28"
set -g @thm_crust "#2a2a37"
set -g @thm_surface_0 "#363646"
set -g @thm_surface_1 "#2d4f67"
set -g @thm_surface_2 "#727169"
set -g @thm_overlay_0 "#54546d"
set -g @thm_overlay_1 "#54546d"
set -g @thm_overlay_2 "#54546d"
set -g @thm_subtext_0 "#c8c093"
set -g @thm_subtext_1 "#dcd7ba"
set -g @thm_red "#e82424"
set -g @thm_maroon "#e82424"
set -g @thm_peach "#ffa066"
set -g @thm_yellow "#e6c384"
set -g @thm_green "#98bb6c"
set -g @thm_teal "#6a9589"
set -g @thm_sky "#6a9589"
set -g @thm_sapphire "#7e9cd8"
set -g @thm_blue "#7e9cd8"
set -g @thm_lavender "#7e9cd8"
set -g @thm_mauve "#957fb8"
set -g @thm_pink "#d27e99"
set -g @thm_flamingo "#e82424"
set -g @thm_rosewater "#dcd7ba"

