set -g @thm_bg "#191724"
set -g @thm_fg "#e0def4"
set -g @thm_mantle "#1f1d2e"
set -g @thm_crust "#1f1d2e"
set -g @thm_surface_0 "#26233a"
set -g @thm_surface_1 "#26233a"
set -g @thm_surface_2 "#26233a"
set -g @thm_overlay_0 "#6e6a86"
set -g @thm_overlay_1 "#908caa"
set -g @thm_overlay_2 "#908caa"
set -g @thm_subtext_0 "#908caa"
set -g @thm_subtext_1 "#e0def4"
set -g @thm_red "#eb6f92"
set -g @thm_maroon "#eb6f92"
set -g @thm_peach "#ebbcba"
set -g @thm_yellow "#f6c177"
set -g @thm_green "#9ccfd8"
set -g @thm_teal "#9ccfd8"
set -g @thm_sky "#9ccfd8"
set -g @thm_sapphire "#31748f"
set -g @thm_blue "#31748f"
set -g @thm_lavender "#31748f"
set -g @thm_mauve "#c4a7e7"
set -g @thm_pink "#c4a7e7"
set -g @thm_flamingo "#eb6f92"
set -g @thm_rosewater "#e0def4"

