set -g @thm_bg "#1e2030"
set -g @thm_fg "#c8d3f5"
set -g @thm_mantle "#222436"
set -g @thm_crust "#1e2030"
set -g @thm_surface_0 "#2f334d"
set -g @thm_surface_1 "#3b4261"
set -g @thm_surface_2 "#444a72"
set -g @thm_overlay_0 "#444a72"
set -g @thm_overlay_1 "#545c7e"
set -g @thm_overlay_2 "#737aa2"
set -g @thm_subtext_0 "#828bb8"
set -g @thm_subtext_1 "#c8d3f5"
set -g @thm_red "#ff757f"
set -g @thm_maroon "#ff757f"
set -g @thm_peach "#ff966c"
set -g @thm_yellow "#ffc777"
set -g @thm_green "#c3e88d"
set -g @thm_teal "#86e1fc"
set -g @thm_sky "#86e1fc"
set -g @thm_sapphire "#82aaff"
set -g @thm_blue "#82aaff"
set -g @thm_lavender "#82aaff"
set -g @thm_mauve "#c099ff"
set -g @thm_pink "#fca7ea"
set -g @thm_flamingo "#ff757f"
set -g @thm_rosewater "#c8d3f5"
