# vim:ft=kitty

## name:     E-Ink
## author:   Algilbert Gomez (https://github.com/alexxGmZ)
## license:  MIT
## upstream: https://github.com/alexxGmZ/e-ink.kitty/blob/main/E-Ink.conf
## blurb:    A grayscale theme aiming to imitate e-ink displays.

foreground #333333
background #CCCCCC
selection_foreground none
selection_background #AEAEAE

cursor none

# black
color0  #4a4a4a
color8  #474747

# red
color1  #9a9a9a
color9  #9a9a9a

# green
color2  #7c7c7c
color10 #7c7c7c

# yellow
color3  #909090
color11 #868686

# blue
color4  #686868
color12 #686868

# magenta
color5  #5e5e5e
color13 #5e5e5e

# cyan
color6  #727272
color14 #727272

# black
color7  #333333
color15 #333333

