$bg = rgb(11111b)
$bgalt = rgb(181825)
$bgtray = rgb(1e1e2e)
$fg = rgb(cdd6f4)
$fgsoft = rgb(cdd6f4)
$fgsoftAlpha = cdd6f4
$border = rgb(313244)
$gray = rgb(6c7086)
$black = rgb(11111b)
$blue = rgb(89b4fa)
$blueAlpha = 89b4fa
$bluedark = rgb(89b4fa)
$pink = rgb(f5c2e7)
$pinkdark = rgb(cba6f7)
$green = rgb(a6e3a1)
$greenAlpha = a6e3a1
$greendark = rgb(a6e3a1)
$red = rgb(f38ba8)
$reddark = rgb(f38ba8)
$redcritical = rgb(f38ba8)
$orange = rgb(fab387)
$accent = rgb(fab387)
$accentAlpha = fab387
