$bg = rgb(cccccc)
$bgalt = rgb(c2c2c2)
$bgtray = rgb(b8b8b8)
$fg = rgb(333333)
$fgsoft = rgb(333333)
$fgsoftAlpha = 333333
$border = rgb(aeaeae)
$gray = rgb(4a4a4a)
$black = rgb(cccccc)
$blue = rgb(686868)
$blueAlpha = 686868
$bluedark = rgb(686868)
$pink = rgb(5e5e5e)
$pinkdark = rgb(5e5e5e)
$green = rgb(7c7c7c)
$greenAlpha = 7c7c7c
$greendark = rgb(7c7c7c)
$red = rgb(9a9a9a)
$reddark = rgb(9a9a9a)
$redcritical = rgb(9a9a9a)
$orange = rgb(909090)
$accent = rgb(909090)
$accentAlpha = 909090

