$bg = rgb(272e33)
$bgalt = rgb(2e383c)
$bgtray = rgb(374145)
$fg = rgb(d3c6aa)
$fgsoft = rgb(d3c6aa)
$fgsoftAlpha = d3c6aa
$border = rgb(414b50)
$gray = rgb(7a8478)
$black = rgb(272e33)
$blue = rgb(7fbbb3)
$blueAlpha = 7fbbb3
$bluedark = rgb(7fbbb3)
$pink = rgb(d699b6)
$pinkdark = rgb(d699b6)
$green = rgb(a7c080)
$greenAlpha = a7c080
$greendark = rgb(a7c080)
$red = rgb(e67e80)
$reddark = rgb(e67e80)
$redcritical = rgb(e67e80)
$orange = rgb(e69875)
$accent = rgb(e69875)
$accentAlpha = e69875
$font = JetBrainsMono Nerd Font
