$bg = rgb(141617)
$bgalt = rgb(1d2021)
$bgtray = rgb(282828)
$fg = rgb(d4be98)
$fgsoft = rgb(d4be98)
$fgsoftAlpha = d4be98
$border = rgb(3c3836)
$gray = rgb(928374)
$black = rgb(000000)
$blue = rgb(7daea3)
$blueAlpha = 7daea3
$bluedark = rgb(458588)
$pink = rgb(d3869b)
$pinkdark = rgb(b26286)
$green = rgb(a9b665)
$greenAlpha = a9b665
$greendark = rgb(689d68)
$red = rgb(ea6962)
$reddark = rgb(cc241d)
$redcritical = rgb(b22222)
$orange = rgb(e78a4e)
$accent = rgb(e78a4e)
$accentAlpha = e78a4e
