$bg = rgb(141617)
$bgalt = rgb(1d2021)
$bgtray = rgb(282828)
$fg = rgb(ebdbb2)
$fgsoft = rgb(ebdbb2)
$fgsoftAlpha = dbdbb2
$border = rgb(3c3836)
$gray = rgb(928374)
$black = rgb(141617)
$blue = rgb(83a598)
$blueAlpha = 83a598
$bluedark = rgb(83a598)
$pink = rgb(d3869b)
$pinkdark = rgb(d3869b)
$green = rgb(b8bb26)
$greenAlpha = b8bb26
$greendark = rgb(b8bb26)
$red = rgb(fb4934)
$reddark = rgb(fb4934)
$redcritical = rgb(fb4934)
$orange = rgb(fe8019)
$accent = rgb(fe8019)
$accentAlpha = f38019
