$bg = rgb(16161d)
$bgalt = rgb(1f1f28)
$bgtray = rgb(2a2a37)
$fg = rgb(dcd7ba)
$fgsoft = rgb(dcd7ba)
$fgsoftAlpha = dcd7ba
$border = rgb(363646)
$gray = rgb(54546d)
$black = rgb(16161d)
$blue = rgb(7e9cd8)
$blueAlpha = 7e9cd8
$bluedark = rgb(7e9cd8)
$pink = rgb(d27e99)
$pinkdark = rgb(d27e99)
$green = rgb(98bb6c)
$greenAlpha = 98bb6c
$greendark = rgb(98bb6c)
$red = rgb(e82424)
$reddark = rgb(e82424)
$redcritical = rgb(e82424)
$orange = rgb(ffa066)
$accent = rgb(ffa066)
$accentAlpha = ffa066
