$bg = rgb(191724)
$bgalt = rgb(1f1d2e)
$bgtray = rgb(1f1d2e)
$fg = rgb(e0def4)
$fgsoft = rgb(e0def4)
$fgsoftAlpha = e0def4
$border = rgb(26233a)
$gray = rgb(908caa)
$black = rgb(191724)
$blue = rgb(31748f)
$blueAlpha = 31748f
$bluedark = rgb(31748f)
$pink = rgb(c4a7e7)
$pinkdark = rgb(c4a7e7)
$green = rgb(9ccfd8)
$greenAlpha = 9ccfd8
$greendark = rgb(9ccfd8)
$red = rgb(eb6f92)
$reddark = rgb(eb6f92)
$redcritical = rgb(eb6f92)
$orange = rgb(ebbcba)
$accent = rgb(ebbcba)
$accentAlpha = dbbcba
