$bg = rgb(1e2030)
$bgalt = rgb(222436)
$bgtray = rgb(2f334d)
$fg = rgb(c8d3f5)
$fgsoft = rgb(c8d3f5)
$fgsoftAlpha = c8d3f5
$border = rgb(3b4261)
$gray = rgb(737aa2)
$black = rgb(1e2030)
$blue = rgb(82aaff)
$blueAlpha = 82aaff
$bluedark = rgb(82aaff)
$pink = rgb(fca7ea)
$pinkdark = rgb(fca7ea)
$green = rgb(c3e88d)
$greenAlpha = c3e88d
$greendark = rgb(c3e88d)
$red = rgb(ff757f)
$reddark = rgb(ff757f)
$redcritical = rgb(ff757f)
$orange = rgb(ff966c)
$accent = rgb(ff966c)
$accentAlpha = ff966c

